LocalDropshipping.Web/Controllers/API/ProfilesController.cs
using LocalDropshipping.Web.Data.Entities;
using LocalDropshipping.Web.Dtos;
using LocalDropshipping.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LocalDropshipping.Web.Controllers.API
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ProfilesController : ControllerBase
    {
        private readonly IProfilesService service;

        public ProfilesController(IProfilesService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            return Ok(service.GetAllProfiles());
        }

        [HttpGet("{id}")]
        public IActionResult GetById(string id)
        {
            return Ok(service.GetProfileById(id));
        }

        [HttpPost]
        public IActionResult Post(ProfilesDto profilesDto)
        {
            Profiles profile = profilesDto.ToEntity();
            service.Add(profile);
            return Ok();
        }

    }
}

LocalDropshipping.Web/Controllers/API/SellerController.cs
using LocalDropshipping.Web.Data.Entities;
using LocalDropshipping.Web.Dtos;
using LocalDropshipping.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace LocalDropshipping.Web.Controllers.API
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class SellerController : ControllerBase
    {
        private readonly IOrderService orderService;
        private readonly IWithdrawalService withdrawalsService;

        public SellerController(IOrderService orderService, IWithdrawalService withdrawalsService)
        {
            this.orderService = orderService;
            this.withdrawalsService = withdrawalsService;

        }

        #region Order


        [HttpGet]
        public IActionResult GetAllOrders()
        {
            return Ok(orderService.GetAll());
        }

        [HttpGet("id")]
        public IActionResult GetOrderById(int id)
        {
            return Ok(orderService.GetById(id));
        }

        [HttpPost]
        public IActionResult AddOrder(OrderDto orderDto)
        {
            Order order = orderDto.ToEntity();
            orderService.Add(order);
            return Ok();
        }

        [HttpDelete("{id}")]
        public IActionResult DeleteOrder(int id)
        {
            orderService.Delete(id);
            return Ok();
        }

        [HttpPost("{id}")]
        public IActionResult UpdateOrder(int id, OrderDto orderDto)
        {
            Order order = orderDto.ToEntity();
            orderService.Update(id, orderDto);
            return Ok();
        }
        #endregion

        #region Withdrawal
        [HttpGet("{id}")]
        public IActionResult getWithdrawalById(int id)
        {
            return Ok(withdrawalsService.GetWithdrawalRequestsById(id));
        }

        [HttpGet("{email}")]
        public IActionResult getWithrawalByUserId(string email)
        {
            return Ok(withdrawalsService.GetWithdrawalRequestsByUserEmail(email));
        }

        [HttpPost]
        public IActionResult ProcessWithdrawal(ProcessWidrawalDto processDto)
        {
            var withdrawal = withdrawalsService.ProcessWithdrawal(processDto);
            if (withdrawal != null)
            {
                return Ok(withdrawal);
            }
            return NotFound();
        }
        #endregion


    }
}

LocalDropshipping.Web/Controllers/PublicController.cs
using LocalDropshipping.Web.Helpers.Constants;
using LocalDropshipping.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LocalDropshipping.Web.Controllers
{
    public class PublicController : Controller
    {
        #region About Us
        public IActionResult AboutUs()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion

        #region Contact Us
        public IActionResult ContactUs()
        {
            try
            {
                return View();

            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion

        #region Terms and Conditions
        public IActionResult TermAndCondition()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion

        #region PrivacyPolicy
        public IActionResult PrivacyPolicy()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion

        #region FAQs
        public IActionResult Faq()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion

        #region Error
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion

        #region LandingPage
        public IActionResult LandingPage()
        {
            return View();
        }
        #endregion


        #region Local Sourcing
        public IActionResult LocalSourcing()
        {
            return View();
        }

        #endregion

        #region CHina Sourcing
        public IActionResult ChinaSourcing()
        {
            return View();
        }
        #endregion

        #region
        public IActionResult FulFillment()
        {
            return View();
        }


        #endregion



        #region AuthrizationFailed
        public IActionResult AuthorizationFailed()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion

        #region GuideLines
        public IActionResult GuideLines()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Register, Constants.AdminActionMethods.Seller);
            }
        }
        #endregion
    }
}

LocalDropshipping.Web/Controllers/SellerController.cs
using LocalDropshipping.Web.Attributes;
using LocalDropshipping.Web.Data;
using LocalDropshipping.Web.Data.Entities;
using LocalDropshipping.Web.Dtos;
using LocalDropshipping.Web.Enums;
using LocalDropshipping.Web.Exceptions;
using LocalDropshipping.Web.Extensions;
using LocalDropshipping.Web.Helpers;
using LocalDropshipping.Web.Helpers.Constants;
using LocalDropshipping.Web.Helpers.Inventory;
using LocalDropshipping.Web.Models;
using LocalDropshipping.Web.Models.Inventory;
using LocalDropshipping.Web.Models.ProductViewModels;
using LocalDropshipping.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Configuration;
using Org.BouncyCastle.Asn1.X509;
using System.IO.Compression;
using System.Security.Claims;

namespace LocalDropshipping.Web.Controllers
{
    public class SellerController : Controller
    {
        private readonly IProfilesService _profileService;
        private readonly IUserService _userService;
        private readonly IAccountService _accountService;
        private readonly IOrderService _orderService;
        private readonly IProductsService _productsService;
        private readonly IWishListService _wishlistService;
        private readonly IProductVariantService _productVariantService;
        private readonly UserManager<User> _userManager;
        private readonly IConsumerService _consumerService;
        private readonly IOrderItemService _orderItemService;
        private readonly IFocSettingService _focSettingService;
        private readonly LocalDropshippingContext _context;
        private readonly IWebHostEnvironment _env;
        private readonly IInventoryService _inventoryService;
        private readonly ICategoryService _categoryService;
        private readonly SignInManager<User> _signInManager;
        private readonly IWithdrawalService _withdrawlsService;
        private readonly IAdminService _service;
        private readonly ICourierService _courierService;
        private readonly IProfilesService _profilesService;
        private readonly IReportService _reportService;
        private readonly IWalletService _walletService;
        private readonly IWholesaleService _wholesaleService;
        private readonly string _system = "system@focfulfillment.com";
        private readonly LocalDropshippingContext context;

        private User _currentUser { get => (User)HttpContext.Items["CurrentUser"]; }
        private bool _isLoggedIn { get => HttpContext.User.Identity.IsAuthenticated; }
        public SellerController(IAccountService accountService, IProfilesService profileService, IUserService userService, IOrderService orderService, UserManager<User> userManager, IWishListService wishList, IProductsService productsService, IProductVariantService productVariantService, IConsumerService consumerService, IOrderItemService orderItemService, IFocSettingService focSettingService, SignInManager<User> signInManager, ICategoryService categoryService, IWithdrawalService withdrawlsService, IAdminService service, ICourierService courierService, IProfilesService profilesService, IReportService reportService, IWalletService walletService, IWholesaleService wholesaleService,LocalDropshippingContext context,IWebHostEnvironment env,IInventoryService inventoryService)
        {
            _service = service;
            _courierService = courierService;
            _profilesService = profilesService;
            _reportService = reportService;
            _walletService = walletService;
            _accountService = accountService;
            _profileService = profileService;
            _userService = userService;
            _orderService = orderService;
            _productsService = productsService;
            _wishlistService = wishList;
            _productVariantService = productVariantService;
            _userManager = userManager;
            _consumerService = consumerService;
            _orderItemService = orderItemService;
            _focSettingService = focSettingService;
            _signInManager = signInManager;
            _categoryService = categoryService;
            _withdrawlsService = withdrawlsService;
            _wholesaleService = wholesaleService;
            _context = context;
            _env = env;
            _inventoryService = inventoryService;
        }


        #region Accounts
        public IActionResult Register()
        {
            if (_isLoggedIn)
            {
                if (_currentUser.IsSeller)
                {
                    if (!_currentUser.EmailConfirmed)
                        return RedirectToAction("VerificationEmailSent", "Seller");

                    if (!_currentUser.IsProfileCompleted)
                        return RedirectToAction("ProfileVerification", "Seller");

                    return RedirectToAction("SellerDashboard", "Seller");
                }
                if (_currentUser.IsAdmin || _currentUser.IsSuperAdmin)
                    return RedirectToAction("Dashboard", "Admin");

            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(SignupViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    User user = new User
                    {
                        Email = model.Email.ToLower().Trim(),
                        UserName = model.Email.Substring(0, model.Email.IndexOf("@")),
                        Fullname = model.FullName,
                        PhoneNumber = model.PhoneNumber,
                        IsSeller = true,
                        CreatedBy = _system,
                        CreatedDate = DateTime.Now,
                        UpdatedDate = DateTime.Now,
                    };
                    var userExist = _userService.CheckEmailExist(user.Email);
                    if (userExist)
                    {
                        ModelState.AddModelError("Email", "Email already exist.");
                        return View(model);
                    }
                    var result = await _accountService.RegisterAsync(user, model.Password);
                    if (result.Succeeded)
                    {
                        TempData.Add("EmailSent", true);
                        return RedirectToAction("VerificationEmailSent");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            if (error.Code == "DuplicateUserName")
                            {
                                ModelState.AddModelError("", string.Join(": ", "DuplicateEmail", "Email already exists"));
                            }
                            else
                            {
                                ModelState.AddModelError("", string.Join(": ", error.Code, error.Description));
                            }
                        }
                    }
                }
                return View(model);
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.FailedToRegister;
                return RedirectToAction(Constants.AdminActionMethods.ProductionErrorView, Constants.AdminActionMethods.Seller);
            }
        }

        public IActionResult VerificationEmailSent()
        {
            try
            {
                if (_isLoggedIn)
                {
                    if (!_currentUser.EmailConfirmed)
                        return View();
                    if (!_currentUser.IsProfileCompleted)
                        return RedirectToAction("ProfileVerification", "Seller");

                    return RedirectToAction("SellerDashboard", "Seller");
                }
                if (TempData.ContainsKey("EmailSent") && (bool)TempData["EmailSent"])
                {
                    return View();
                }
                return RedirectToAction("Login", "Seller");
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Shop, Constants.AdminActionMethods.Seller);
            }
        }

        public async Task<IActionResult> EmailVerification(string userId, string token)
        {
            try
            {
                if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(token))
                {
                    return RedirectToAction("InvalidVerificationLink");
                }
                var isVerified = await _accountService.ConfirmEmailAsync(userId, token);
                if (isVerified)
                {
                    return RedirectToAction("Login","Seller");
                }
                else
                {
                    return RedirectToAction("InvalidVerificationLink");
                }
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;
                return RedirectToAction(Constants.AdminActionMethods.Shop, Constants.AdminActionMethods.Seller);
            }
        }

        public IActionResult EmailVerified()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                TempData[Constants.AdminTempData.NotificationMessage] = Constants.ErrorMessage.CommonErrorMessage;

LocalDropshipping.Web/Views/Seller/EmailVerified.cshtml
@{
    Layout = "_LayoutGuests";
    ViewBag.Title = "FOCFulfillment - Email Verified";

    ViewData["Title"] = "Email Verified";
}
<div class="sign-up-box">
    <div class="container">
        <div class="row my-4">
            <div class="col-12">
                <h3>Your email has been verified successfully</h3>
                <p></p>
                <p>Please <a asp-action="Login" asp-controller="Seller">Login</a> to continue...</p>
            </div>
        </div>
    </div>
</div>

LocalDropshipping.Web/Views/Seller/ForgotPasswordMessage.cshtml
@{
    ViewBag.Title = "FOCFulfillment - Forgot Password Message";
}
<div class="container">
    <div class="row my-4">
        <h3 style="margin-bottom:30px;">Please check your email!</h3>
    </div>
</div>

LocalDropshipping.Web/Views/Seller/Login.cshtml
@model LoginViewModel
@{
    ViewBag.Title = "FOCFulfillment - Login";
    Layout = "_LayoutGuests";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Fastkart">
    <meta name="keywords" content="Fastkart">
    <meta name="author" content="Fastkart">
    <link rel="icon" href="../assets/images/favicon/1.png" type="image/x-icon">
    <title>Log In</title>

    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">

    <!-- bootstrap css -->
    <link id="rtl-link" rel="stylesheet" type="text/css" href="../assets/css/vendors/bootstrap.css">

    <!-- font-awesome css -->
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/font-awesome.css">

    <!-- feather icon css -->
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/feather-icon.css">

    <!-- slick css -->
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="../assets/css/vendors/slick/slick-theme.css">

    <!-- Iconly css -->
    <link rel="stylesheet" type="text/css" href="../assets/css/bulk-style.css">

    <!-- Template css -->
    <link id="color-link" rel="stylesheet" type="text/css" href="../assets/css/style.css">
    <!-- custom css -->
    <link rel="stylesheet" href="../assets/css/custom.css">
    
            <link rel="stylesheet" href="../assets/css/layout-fulfil-china.css">


     <style>
        header .navbar.navbar-expand-xl .navbar-nav .nav-link{
            padding: 12px 15px;
        }

        .login-img img{
            border-radius: 10px;
        }

        @@media screen and (max-width: 1440px) and (min-width: 1200px){
            header .navbar.navbar-expand-xl .navbar-nav .nav-link {
    padding: 12px 1px;
}
        }
        @@media screen and (min-width:1441px){
            .login-img img{
                max-width: 75%;
            }
        }

    </style> 
</head>

<body>
    <!-- Breadcrumb Section Start -->
    <div>
        <div class="container-fluid-lg text-left pt-4">
            <div class="row login-heading local-china-1-text animate-heading-6">
                <h1>Login</h1>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->
    <!-- log in section start -->
    <section class="log-in-section background-image-2 section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row this-row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 d-lg-block d-none ms-auto">
                    <div class="image-contain login-img">
                        <img src="../assets/images/landing-page/foc-img-1.jpeg" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h3>Welcome To FOCFulfillment</h3>
                            <h4>Log In Your Account</h4>
                        </div>

                        <div class="input-box">
                            <form asp-action="Login" asp-route-returnUrl="@Context.Request.Query["ReturnUrl"]" class="row g-4">
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                        <input asp-for="Email" class="form-control" id="email" placeholder="Email Address" value="" minlength="2" maxlength="50">
                                        <label>Email Address</label>
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form custom-input">
                                        <input asp-for="Password" type="password" id="password" class="form-control" id="password" placeholder="Password" value="" minlength="6" maxlength="35">
                                        <label for="password">Password</label>
                                        <span><i id="toggle-password" class="fas fa-eye-slash"></i></span>
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="forgot-box">
                                        <div class="form-check ps-0 m-0 remember-box">
                                            <input asp-for="RememberMe" class="checkbox_animated check-box" type="checkbox"
                                                   id="flexCheckDefault" name="RememberMe">
                                            <label class="form-check-label" for="flexCheckDefault">Remember me</label>
                                        </div>
                                        <a href="ForgotPassword" class="forgot-password">Forgot Password?</a>
                                    </div>
                                </div>
                                <div class="validation-summary-errors col-12">
                                    @* @Html.ValidationSummary(false, "", new { @class = "text-danger" }) *@
                                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-animation w-100 justify-content-center" type="submit">
                                        Log
                                        In
                                    </button>
                                </div>
                            </form>
                        </div>

                       @*  <div class="other-log-in">
                            <h6>or</h6>
                        </div>

                        <div class="log-in-button">
                            <ul>
                                <li>
                                    <a asp-action="LoginWithGoogle" class="btn google-button w-100">
                                        <img src="../assets/images/inner-page/google.png" class="blur-up lazyload"
                                             alt="">Continue with Google
                                    </a>
                                </li>
                            </ul>
                        </div>

                        <div class="other-log-in">
                            <h6></h6>
                        </div> *@

@*                         <div class="sign-up-box">
                            <h4>Don't have an account?</h4>
                            <a asp-action="Register" asp-controller="Seller">Sign Up</a>

                        </div> *@
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- log in section end -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/backend-assets/js/notify/bootstrap-notify.min.js"></script>
    <script>

        var notificationMessage = '@TempData["notificationMessage"]';

        console.log(notificationMessage);

        if (notificationMessage) {
            var notify = $.notify('<i class="fas fa-bell"></i> ' + notificationMessage, {
                type: 'theme',
                allow_dismiss: true,
                delay: 2000,
                showProgressbar: true,
                timer: 100,
                animate: {
                    enter: 'animated fadeInDown',
                    exit: 'animated fadeOutUp'
                }
            });

            '@TempData.Remove("notificationMessage")';
        }

        $(document).ready(function () {
            $('#toggle-password').click(function () {
                const passwordField = $('#password');

                if (passwordField.attr('type') === 'password') {
                    passwordField.attr('type', 'text');
                    $('#toggle-password').removeClass('fa-eye-slash').addClass('fa-eye');
                } else {
                    passwordField.attr('type', 'password');
                    $('#toggle-password').removeClass('fa-eye').addClass('fa-eye-slash');
                }
            });
        });

        document.addEventListener("DOMContentLoaded", function () {
            var emailCookie = getCookie("RememberMeEmail");
            var passwordCookie = getCookie("RememberMePassword");

            if (emailCookie) {
                emailCookie = decodeURIComponent(emailCookie);
                document.getElementById("email").value = emailCookie;
            }

            if (passwordCookie) {
                passwordCookie = decodeURIComponent(passwordCookie);
                document.getElementById("password").value = passwordCookie;
            }
        });

        function getCookie(name) {
            var value = "; " + document.cookie;
            var parts = value.split("; " + name + "=");

            if (parts.length === 2) {
                return parts.pop().split(";").shift();
            }

            return null;
        }


    </script>
</body>
</html>

LocalDropshipping.Web/Views/Seller/RegisterVarify.cshtml
@{
    ViewBag.Title = "FOCFulfillment - Register Verify";
}
@if (TempData["RegistrationConfirmation"] != null)
{
    <div class="alert alert-success">
        @TempData["RegistrationConfirmation"]
    </div>
}

LocalDropshipping.Web/Views/Seller/Subscribe.cshtml
@{
    ViewBag.Title = "FOCFulfillment - Subscribe";
    Layout = "_LayoutSellerApproval";
}
<div class="container">
    <div class="row my-4">
        <h3>Please transact Rs.5000/- Rs on the following accounts and share the transaction receipt on the specified email.</h3>
        <p></p>
        <p>
            <strong>Account Title</strong>: AHMED FURQAN
            <br />
            <strong>Bank Name</strong>: Meezan Bank
            <br />
            <strong>Account Number</strong>: 42010102642160
            <br />
            <strong>IBAN</strong>: PK19MEZN0042010102642160
            <br />
        </p>
        <p>Please share the transaction receipt on focfulfillment@gmail.com</p>
        <hr />
        <small>Our team will verify the payment and will activate your account in next 48 hours. If you are getting trouble in activating your account <a asp-controller="Public" asp-action="ContactUs">Contact Us</a></small>

    </div>
</div>

LocalDropshipping.Web/Views/Seller/contactUsMessage.cshtml
@{
	Layout = "_LayoutGuests";
	ViewBag.Title = "FOCFulfillment - Contact-Us Message";

}
<div style="text-align:center;margin: 100px 0px 100px 0px; ">
	<h2 style="text-transform:inherit">
		Thank you for contacting us. We will respond you soon!
	</h2>
</div>